version: '{build}'
image: Visual Studio 2017

environment:
  nodejs_version: 14

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - npm install
  - npm pack

artifacts:
  - path: fuse-sdk-*.tgz

test_script:
  - bash -c "npm install -g fuse-sdk-*.tgz"
  - uno build app
